import React from 'react';
import localFont from 'next/font/local';

import './globals.css';

import QueryProvider from '../providers/QueryProvider';
import Web3Provider from '../providers/Web3Provider';
// eslint-disable-next-line new-cap
const bruno = localFont({
  src: '../../public/fonts/BrunoAceSC.ttf',
  variable: '--bruno-font',
});
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={bruno.className}>
        <QueryProvider>
          <Web3Provider>{children}</Web3Provider>
        </QueryProvider>
      </body>
    </html>
  );
}
