import React, { Suspense } from 'react';
import localFont from 'next/font/local';

import Loading from '@/app/loading';
import styles from '@/app/page.module.css';
import Footer from '@/components/Footer';
import Header from '@/components/Header';

import './globals.css';

import QueryProvider from '../providers/QueryProvider';
import Web3Provider from '../providers/Web3Provider';
// eslint-disable-next-line new-cap
const bruno = localFont({
  src: '../../public/fonts/BrunoAceSC.ttf',
  variable: '--bruno-font',
});
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={bruno.className}>
        <Suspense fallback={<Loading />}>
          <QueryProvider>
            <Web3Provider>
              <div className={styles.wrapper}>
                <Header />
                {children}
                <Footer />
              </div>
            </Web3Provider>
          </QueryProvider>
        </Suspense>
      </body>
    </html>
  );
}
